-- One row per login (per device). The session, not the token, is the thing a user
-- recognises: "my phone", "my laptop at work". Revoking a session is what logout,
-- "log out everywhere" and an admin lock-out all do.
--
-- This table is the source of truth for refresh tokens. Redis stays in front of the
-- access-token check for speed, but losing Redis must not resurrect a revoked session.
CREATE TABLE user_sessions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Exposed to the client so it can revoke one specific device
    public_id         UUID         NOT NULL,
    user_id           BIGINT       NOT NULL,
    -- jti of the refresh token currently valid for this session; replaced on every rotation
    refresh_token_id  VARCHAR(64)  NOT NULL,
    ip_address        VARCHAR(45),
    user_agent        VARCHAR(255),
    last_used_at      TIMESTAMPTZ  NOT NULL,
    expires_at        TIMESTAMPTZ  NOT NULL,
    -- NULL means the session is live; set once, never cleared
    revoked_at        TIMESTAMPTZ,
    version           BIGINT       NOT NULL DEFAULT 0,
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
    is_deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ,
    CONSTRAINT uk_user_sessions_public_id UNIQUE (public_id),
    -- A refresh token id identifies exactly one session, which is what makes
    -- replay of a rotated token detectable
    CONSTRAINT uk_user_sessions_refresh_token_id UNIQUE (refresh_token_id),
    CONSTRAINT fk_user_sessions_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Listing a user's devices, newest first
CREATE INDEX idx_user_sessions_user_id ON user_sessions (user_id, created_at DESC);
-- Deleting sessions that expired long ago
CREATE INDEX idx_user_sessions_expires_at ON user_sessions (expires_at);
