-- Vendors: the stores that sell on the platform, and the people who act for them.
--
-- Everything a vendor owns later (products, stock, orders, payouts) carries vendor_id,
-- and no query may return a row belonging to another vendor. That rule starts here:
-- vendor_members is the only place that says which user may act for which store, and
-- the application checks it on every vendor-scoped request.
-- See docs/architecture/adr/0014-vendor-data-isolation.md.
CREATE TABLE vendors (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Exposed instead of the sequential id, so vendor ids cannot be guessed or counted
    public_id         UUID         NOT NULL,
    -- Storefront host label: <slug>.groceryecom.com. Lower case, letters, digits and
    -- single hyphens, so it is a valid DNS label and a stable URL.
    slug              VARCHAR(63)  NOT NULL,
    -- The registered business, used on invoices and for payouts
    legal_name        VARCHAR(255) NOT NULL,
    -- What customers see
    display_name      VARCHAR(120) NOT NULL,
    contact_email     VARCHAR(255) NOT NULL,
    contact_phone     VARCHAR(20),
    -- PENDING until an admin decides; only APPROVED may sell
    status            VARCHAR(20)  NOT NULL,
    -- Why an admin rejected or suspended the store; shown to the vendor
    status_reason     VARCHAR(500),
    status_changed_at TIMESTAMPTZ,
    version           BIGINT       NOT NULL DEFAULT 0,
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
    is_deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ,
    CONSTRAINT uk_vendors_public_id UNIQUE (public_id),
    -- Two stores cannot share a storefront address; the unique index is also what the
    -- application relies on when two applications race for the same slug
    CONSTRAINT uk_vendors_slug UNIQUE (slug),
    CONSTRAINT ck_vendors_slug_lowercase CHECK (slug = lower(slug)),
    CONSTRAINT ck_vendors_slug_format CHECK (slug ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'),
    CONSTRAINT ck_vendors_contact_email_lowercase CHECK (contact_email = lower(contact_email)),
    CONSTRAINT ck_vendors_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED'))
);

-- The admin queue: applications waiting for a decision, oldest first
CREATE INDEX idx_vendors_status ON vendors (status, created_at);

-- Who may act for a store. A user with no row here has no access to any vendor data.
CREATE TABLE vendor_members (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id      UUID         NOT NULL,
    vendor_id      BIGINT       NOT NULL,
    -- The identity module's public id, not its primary key: modules are joined by the
    -- identifier that is part of a module's contract, never by another module's
    -- internal key. That is also why there is no foreign key to users here; the
    -- application keeps this consistent, and ADR-0014 records the trade-off.
    user_public_id UUID         NOT NULL,
    -- OWNER applied for the store and may manage it; STAFF is added by an owner later
    member_role    VARCHAR(20)  NOT NULL,
    version        BIGINT       NOT NULL DEFAULT 0,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    is_deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ,
    CONSTRAINT uk_vendor_members_public_id UNIQUE (public_id),
    -- One membership per person per store
    CONSTRAINT uk_vendor_members_vendor_user UNIQUE (vendor_id, user_public_id),
    CONSTRAINT ck_vendor_members_role CHECK (member_role IN ('OWNER', 'STAFF')),
    CONSTRAINT fk_vendor_members_vendor FOREIGN KEY (vendor_id) REFERENCES vendors (id)
);

-- "Which stores may this user act for?" runs on every vendor-scoped request
CREATE INDEX idx_vendor_members_user ON vendor_members (user_public_id);
