-- Vendor licensing: what a store pays to trade on the platform.
--
-- Three tables, three different lifetimes:
--   plans                  reference data, changes rarely, same for everyone
--   vendor_subscriptions   one row per store, the current state of its licence
--   subscription_payments  one row per charge, never updated except to settle it
--
-- Money is stored as an integer count of the currency's smallest unit plus a currency
-- code (shared.money.Money). A price is never a floating point number.
CREATE TABLE plans (
    id                      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id               UUID         NOT NULL,
    -- What code and clients refer to, so a price change does not break an integration
    code                    VARCHAR(30)  NOT NULL,
    name                    VARCHAR(80)  NOT NULL,
    description             VARCHAR(500),
    price_amount_minor      BIGINT       NOT NULL,
    price_currency          VARCHAR(3)   NOT NULL,
    billing_period          VARCHAR(10)  NOT NULL,
    -- Days a store may trade before paying anything. 0 means pay first.
    trial_days              INTEGER      NOT NULL DEFAULT 0,
    -- NULL means no limit. Enforced by catalog and vendor staff management later.
    max_products            INTEGER,
    max_staff               INTEGER,
    -- The platform's cut of each order, in basis points: 250 = 2.5%
    commission_basis_points INTEGER      NOT NULL,
    -- False hides a plan from the public list without deleting it: an old price kept
    -- for the vendors already on it, or one negotiated for a single chain
    is_public               BOOLEAN      NOT NULL DEFAULT TRUE,
    version                 BIGINT       NOT NULL DEFAULT 0,
    is_active               BOOLEAN      NOT NULL DEFAULT TRUE,
    is_deleted              BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ  NOT NULL,
    updated_at              TIMESTAMPTZ,
    CONSTRAINT uk_plans_public_id UNIQUE (public_id),
    CONSTRAINT uk_plans_code UNIQUE (code),
    CONSTRAINT ck_plans_price_not_negative CHECK (price_amount_minor >= 0),
    CONSTRAINT ck_plans_billing_period CHECK (billing_period IN ('MONTHLY', 'YEARLY')),
    CONSTRAINT ck_plans_trial_days CHECK (trial_days >= 0),
    CONSTRAINT ck_plans_commission CHECK (commission_basis_points BETWEEN 0 AND 10000),
    CONSTRAINT ck_plans_limits CHECK (
        (max_products IS NULL OR max_products > 0) AND (max_staff IS NULL OR max_staff > 0))
);

-- One licence per store. Renewing extends this row rather than adding another, so
-- "is this store paid up?" is one lookup and can never return two answers. The history
-- of what was charged lives in subscription_payments.
CREATE TABLE vendor_subscriptions (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id            UUID         NOT NULL,
    -- The vendor module's public id: modules are joined by what a module publishes
    vendor_public_id     UUID         NOT NULL,
    plan_id              BIGINT       NOT NULL,
    status               VARCHAR(20)  NOT NULL,
    -- The window the store has paid for (or is trialling)
    current_period_start TIMESTAMPTZ  NOT NULL,
    current_period_end   TIMESTAMPTZ  NOT NULL,
    -- How long after the end date the store keeps working while payment is chased.
    -- A shop that cannot sell the morning a card expires is a shop that leaves.
    grace_until          TIMESTAMPTZ  NOT NULL,
    cancelled_at         TIMESTAMPTZ,
    version              BIGINT       NOT NULL DEFAULT 0,
    is_active            BOOLEAN      NOT NULL DEFAULT TRUE,
    is_deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMPTZ  NOT NULL,
    updated_at           TIMESTAMPTZ,
    CONSTRAINT uk_vendor_subscriptions_public_id UNIQUE (public_id),
    -- A store cannot hold two licences at once
    CONSTRAINT uk_vendor_subscriptions_vendor UNIQUE (vendor_public_id),
    CONSTRAINT fk_vendor_subscriptions_plan FOREIGN KEY (plan_id) REFERENCES plans (id),
    CONSTRAINT ck_vendor_subscriptions_status CHECK (
        status IN ('PENDING_PAYMENT', 'TRIALING', 'ACTIVE', 'PAST_DUE', 'EXPIRED', 'CANCELLED')),
    CONSTRAINT ck_vendor_subscriptions_period CHECK (current_period_end >= current_period_start),
    CONSTRAINT ck_vendor_subscriptions_grace CHECK (grace_until >= current_period_end)
);

-- The job that expires licences scans by end date, so it must not read every row
CREATE INDEX idx_vendor_subscriptions_due ON vendor_subscriptions (grace_until)
    WHERE status IN ('TRIALING', 'ACTIVE', 'PAST_DUE');

-- One row per charge. Money that was asked for, and whether it arrived.
CREATE TABLE subscription_payments (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id          UUID         NOT NULL,
    subscription_id    BIGINT       NOT NULL,
    amount_minor       BIGINT       NOT NULL,
    currency           VARCHAR(3)   NOT NULL,
    -- How the store is paying: MANUAL today, a gateway name later
    provider           VARCHAR(30)  NOT NULL,
    -- The provider's id for this charge. Unique, and that uniqueness is what makes
    -- confirming a payment twice - a retried webhook - harmless.
    provider_reference VARCHAR(100) NOT NULL,
    status             VARCHAR(20)  NOT NULL,
    paid_at            TIMESTAMPTZ,
    failure_reason     VARCHAR(255),
    version            BIGINT       NOT NULL DEFAULT 0,
    is_active          BOOLEAN      NOT NULL DEFAULT TRUE,
    is_deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ  NOT NULL,
    updated_at         TIMESTAMPTZ,
    CONSTRAINT uk_subscription_payments_public_id UNIQUE (public_id),
    CONSTRAINT uk_subscription_payments_reference UNIQUE (provider_reference),
    CONSTRAINT fk_subscription_payments_subscription
        FOREIGN KEY (subscription_id) REFERENCES vendor_subscriptions (id),
    CONSTRAINT ck_subscription_payments_status CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_subscription_payments_amount CHECK (amount_minor >= 0)
);

-- A store's billing history, newest first
CREATE INDEX idx_subscription_payments_subscription
    ON subscription_payments (subscription_id, created_at DESC);

-- Reference data, not test data: the platform sells these three plans from day one.
-- Prices are in sen (MYR minor units): 4900 = RM 49.00 per month.
INSERT INTO plans (public_id, code, name, description, price_amount_minor, price_currency,
                   billing_period, trial_days, max_products, max_staff, commission_basis_points,
                   is_public, created_at)
VALUES
    (gen_random_uuid(), 'STARTER', 'Starter',
     'For a new store finding its first customers. Two weeks free, then RM 49 a month.',
     4900, 'MYR', 'MONTHLY', 14, 100, 2, 500, TRUE, now()),
    (gen_random_uuid(), 'GROWTH', 'Growth',
     'For a store with a steady order flow. More products, more staff, a lower commission.',
     14900, 'MYR', 'MONTHLY', 0, 1000, 10, 350, TRUE, now()),
    (gen_random_uuid(), 'SCALE', 'Scale',
     'For a chain. No catalogue limit and the lowest commission.',
     39900, 'MYR', 'MONTHLY', 0, NULL, NULL, 200, TRUE, now());
