-- Payment gateway credentials, entered by an admin in the console and changed without a
-- deploy. One row per provider.
--
-- Why they are in the database at all: the platform owner signs up with Razorpay after
-- the software is running, rotates keys when Razorpay asks, and switches from test to
-- live keys on launch day. Putting that in an environment variable makes each of those a
-- release, done by whoever can deploy, at a time that suits the deploy - not the business.
--
-- What that costs, and how it is paid for:
--   * the secret and the webhook secret are stored ENCRYPTED (AES-256-GCM,
--     platform.crypto.SecretCipher). The column holds ciphertext, never the key itself,
--     so a database dump, a backup or a read-only replica does not leak a live key.
--   * the encryption key is NOT here. It comes from the environment
--     (SECRETS_MASTER_KEY), so the database and the key it is protected with never travel
--     together. Losing that variable means re-entering the gateway keys, which is a
--     deliberate trade: an unreadable credential is better than a readable one.
--   * key_id is NOT encrypted. Razorpay's key id is public - the browser needs it to open
--     the checkout - and encrypting a public value only makes it harder to support.
--   * no API ever returns a secret. The admin screen shows the last four characters so a
--     person can tell which key is installed, and nothing more.
CREATE TABLE payment_gateway_credentials (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id             UUID         NOT NULL,
    -- RAZORPAY today; one row per provider, so a second gateway is a row, not a migration
    provider              VARCHAR(30)  NOT NULL,
    -- TEST or LIVE. Kept explicit because "why did no money arrive?" is almost always
    -- test keys left in place after launch.
    mode                  VARCHAR(10)  NOT NULL,
    -- Public: the browser needs it to open the gateway's checkout
    key_id                VARCHAR(100) NOT NULL,
    -- Ciphertext. Never logged, never returned by an API, never in a response DTO.
    key_secret_cipher     TEXT         NOT NULL,
    -- Ciphertext. Used only to verify that a webhook really came from the gateway.
    webhook_secret_cipher TEXT,
    -- False parks a configured gateway without deleting it: switching back to bank
    -- transfer during an outage is then one click, not a key re-entry.
    enabled               BOOLEAN      NOT NULL DEFAULT TRUE,
    -- Who installed these keys. "Who changed the payment configuration?" must have an
    -- answer, and this is the row people will ask about.
    updated_by_user_id    UUID,
    version               BIGINT       NOT NULL DEFAULT 0,
    is_active             BOOLEAN      NOT NULL DEFAULT TRUE,
    is_deleted            BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMPTZ  NOT NULL,
    updated_at            TIMESTAMPTZ,
    CONSTRAINT uk_payment_gateway_credentials_public_id UNIQUE (public_id),
    -- One set of credentials per provider: two would mean two answers to "which key?"
    CONSTRAINT uk_payment_gateway_credentials_provider UNIQUE (provider),
    CONSTRAINT ck_payment_gateway_credentials_provider CHECK (provider IN ('RAZORPAY')),
    CONSTRAINT ck_payment_gateway_credentials_mode CHECK (mode IN ('TEST', 'LIVE'))
);

-- Nothing is seeded. A gateway with no row is a gateway that is not configured, and the
-- platform falls back to bank transfer confirmed by an admin until somebody pastes keys.
