-- Where a vendor's share of a customer's payment goes.
--
-- The platform takes the customer's money and owes most of it to the vendor. That needs
-- a destination per store, and the rules about it are stricter than anything else here:
--
--   * NO BANK DETAILS ARE STORED. The account number and IFSC are sent straight to the
--     gateway, which returns an id for the destination it created. That id is what this
--     table holds. A database dump therefore cannot be used to move anybody's money, and
--     the platform stays out of the compliance scope that storing bank details brings.
--   * The last four digits are kept, unencrypted and alone, so a vendor can recognise
--     which account they set up. Four digits identify nothing by themselves.
--   * A destination is VERIFIED by the gateway, not by us. Until then the vendor's share
--     is held rather than sent, because paying the wrong account is not reversible by an
--     apology.
CREATE TABLE vendor_payout_accounts (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID         NOT NULL,
    -- The vendor module's public id; billing does not reach into its tables
    vendor_public_id    UUID         NOT NULL,
    provider            VARCHAR(30)  NOT NULL,
    -- The gateway's id for this destination (a Razorpay linked account). Not a secret -
    -- it cannot move money on its own - but it is the whole of what we keep.
    provider_account_id VARCHAR(100),
    -- Shown back to the vendor so they can tell which account this is
    account_holder_name VARCHAR(160) NOT NULL,
    bank_name           VARCHAR(120),
    account_last4       VARCHAR(4)   NOT NULL,
    status              VARCHAR(20)  NOT NULL,
    -- Why the gateway or an admin refused it, in words the vendor can act on
    status_reason       VARCHAR(500),
    verified_at         TIMESTAMPTZ,
    version             BIGINT       NOT NULL DEFAULT 0,
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    is_deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ,
    CONSTRAINT uk_vendor_payout_accounts_public_id UNIQUE (public_id),
    -- One destination per store: two would mean two answers to "where does the money go?"
    CONSTRAINT uk_vendor_payout_accounts_vendor UNIQUE (vendor_public_id),
    CONSTRAINT ck_vendor_payout_accounts_provider CHECK (provider IN ('RAZORPAY', 'MANUAL')),
    CONSTRAINT ck_vendor_payout_accounts_status CHECK (
        status IN ('PENDING_VERIFICATION', 'VERIFIED', 'REJECTED', 'SUSPENDED')),
    CONSTRAINT ck_vendor_payout_accounts_last4 CHECK (account_last4 ~ '^[0-9]{4}$')
);

-- The admin queue: destinations waiting on verification, oldest first
CREATE INDEX idx_vendor_payout_accounts_status ON vendor_payout_accounts (status, created_at);
