package com.groceryecom.platform.database;

import com.groceryecom.PostgresIntegrationTest;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * The privileges of the role the application connects as, checked against a real
 * PostgreSQL by running the very file Docker mounts into the database container
 * ({@code ops/postgres/init/01-runtime-role.sql}).
 *
 * <p>Why this test exists: the split between an owner role that migrates and a
 * DML-only role that serves requests is a claim about the database, not about Java.
 * Nothing in the application would fail if the GRANT statements were wrong - the
 * runtime role would simply be able to drop tables, and nobody would notice until
 * an injection flaw or a bad migration used that power.
 *
 * <p>It extends {@link PostgresIntegrationTest} for the embedded server only; it
 * starts no application context, and works in its own database so the schema the
 * other tests migrate is left alone.
 */
class DatabaseRolePrivilegeTest extends PostgresIntegrationTest {

    private static final Path INIT_SCRIPT = Path.of("ops", "postgres", "init", "01-runtime-role.sql");
    private static final String PROBE_DB = "role_privilege_probe";
    private static final String RUNTIME_ROLE = "grocery_app";

    @BeforeAll
    static void createProbeDatabaseAndApplyTheInitScript() throws Exception {
        try (Connection owner = asOwner("postgres"); Statement statement = owner.createStatement()) {
            statement.execute("DROP DATABASE IF EXISTS " + PROBE_DB);
            statement.execute("DROP ROLE IF EXISTS " + RUNTIME_ROLE);
            statement.execute("CREATE DATABASE " + PROBE_DB);
        }

        String initScript = Files.readString(INIT_SCRIPT);
        try (Connection owner = asOwner(PROBE_DB); Statement statement = owner.createStatement()) {
            statement.execute(initScript);
            // A table created after the script ran, standing in for a future migration:
            // ALTER DEFAULT PRIVILEGES has to cover it without anyone re-granting.
            statement.execute("CREATE TABLE orders_probe (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, note TEXT)");
        }
    }

    @AfterAll
    static void dropProbeDatabase() throws Exception {
        try (Connection owner = asOwner("postgres"); Statement statement = owner.createStatement()) {
            statement.execute("DROP DATABASE IF EXISTS " + PROBE_DB);
            statement.execute("DROP ROLE IF EXISTS " + RUNTIME_ROLE);
        }
    }

    @Test
    void theRuntimeRoleCanReadAndWriteRowsInATableCreatedAfterTheGrants() throws Exception {
        try (Connection app = asRuntimeRole(); Statement statement = app.createStatement()) {
            statement.execute("INSERT INTO orders_probe (note) VALUES ('an order')");
            statement.execute("UPDATE orders_probe SET note = 'an amended order'");

            var rows = statement.executeQuery("SELECT note FROM orders_probe");
            assertThat(rows.next()).isTrue();
            assertThat(rows.getString("note")).isEqualTo("an amended order");

            statement.execute("DELETE FROM orders_probe");
        }
    }

    @Test
    void theRuntimeRoleCannotCreateTables() throws Exception {
        try (Connection app = asRuntimeRole(); Statement statement = app.createStatement()) {
            assertThatThrownBy(() -> statement.execute("CREATE TABLE smuggled (id INT)"))
                    .as("the application role must not be able to add to the schema")
                    .isInstanceOf(SQLException.class)
                    .hasMessageContaining("permission denied for schema public");
        }
    }

    @Test
    void theRuntimeRoleCannotDropOrAlterTables() throws Exception {
        try (Connection app = asRuntimeRole(); Statement statement = app.createStatement()) {
            assertThatThrownBy(() -> statement.execute("DROP TABLE orders_probe"))
                    .as("a bug or an injection flaw must not be able to destroy a table")
                    .isInstanceOf(SQLException.class)
                    .hasMessageContaining("must be owner of table orders_probe");

            assertThatThrownBy(() -> statement.execute("ALTER TABLE orders_probe ADD COLUMN sneaky TEXT"))
                    .as("the schema is owned by migrations alone")
                    .isInstanceOf(SQLException.class)
                    .hasMessageContaining("must be owner of table orders_probe");
        }
    }

    @Test
    void theRuntimeRoleHasNoSuperuserOrRoleCreationRights() throws Exception {
        try (Connection app = asRuntimeRole(); Statement statement = app.createStatement()) {
            var attributes = statement.executeQuery(
                    "SELECT rolsuper, rolcreaterole, rolcreatedb FROM pg_roles WHERE rolname = current_user");
            assertThat(attributes.next()).isTrue();
            assertThat(attributes.getBoolean("rolsuper")).as("superuser").isFalse();
            assertThat(attributes.getBoolean("rolcreaterole")).as("create role").isFalse();
            assertThat(attributes.getBoolean("rolcreatedb")).as("create database").isFalse();
        }
    }

    private static Connection asOwner(String database) throws SQLException {
        return DriverManager.getConnection(postgres().getJdbcUrl("postgres", database), "postgres", "postgres");
    }

    /** The embedded server trusts local connections, so no password is needed here. */
    private static Connection asRuntimeRole() throws SQLException {
        return DriverManager.getConnection(postgres().getJdbcUrl(RUNTIME_ROLE, PROBE_DB), RUNTIME_ROLE, "");
    }
}
